### ISSUE TITLE
Hélio Tenore Barroco - Resolução do Desafio

### ISSUE THREAD

**Issue by hbarroco** [DevMasterTeam/desafio-carros#1]
Boa tarde Amigo,

O erro está na classe DetailActivity.java, no evento "OnListClickInteractionListener", abaixo da linha 59(intent.putExtras(bundle);), está faltando o startActivity(startActivity(intent);).

Até mais.

**Comment by DevMasterTeam** [comment]
Faaala, Hélio!

Show! Esse é um dos problemas, mas tem outro logo depois de arrumar esse! Percebeu algo estranho nas chaves que são usadas para passar os valores entre activities?

Abraço!

**Comment by hbarroco** [comment]
Olá Amigo,

Sim, além do problema reportado, não estamos usando a constante criada para o id do carro "CARRO_ID".

Até mais.
