### ISSUE TITLE
Alex Soares - Resolução do Desafio

### ISSUE THREAD

**Issue by asores** [DevMasterTeam/desafio-carros#2]
O erro encontra-se na classe **MainActivity.java**, após a linha 59.
Solução: Acrescentar o código abaixo:
  **startActivity(intent);**

Obrigado!

**Comment by DevMasterTeam** [comment]
Faala Alex!

Show! Esse é um dos problemas, mas tem outro logo depois de arrumar esse! Percebeu algo estranho nas chaves que são usadas para passar os valores entre activities?

Abraço!

**Comment by asores** [comment]
Sim Sim...

Não havia necessidade de usar
  **Bundle bundle = new Bundle();
  bundle.putInt("CarroId", id)**;

Poderia ser:    **intent.putExtra("CarroId", id);**

**Comment by DevMasterTeam** [comment]
Maravilha! :D
