### ISSUE TITLE
Rafael Eduardo Lima - Resolução Desafio

### ISSUE THREAD

**Issue by sudorafa** [DevMasterTeam/desafio-carros#4]
- Após a linha 61 da MainActivity onde passa o extras via bundle de car trazido pelo ID:
`intent.putExtras(bundle);`
faltou startar a activitie:
`startActivity(intent);`
Com a itent estanciada para abrir detalhe:
`Intent intent = new Intent(mContext, DetailsActivity.class);`

- E na linha 58 para boas praticas faltou usar a constante que até já existe **CARRO_ID** para o bundle.

**Comment by DevMasterTeam** [comment]
Boa, Rafa!
Show de bola! São os dois problemas que estão atualmente no código.
Abraço e bons estudos!
